DROP TABLE IF EXISTS PURCHASE_GIFT_CARD;
CREATE TABLE PURCHASE_GIFT_CARD
(
GCARD_ID VARCHAR(4),
CUST_ID INT,
PRICE DECIMAL(5,2),
TRANS_ID INT
);
ALTER TABLE PURCHASE_GIFT_CARD ADD CONSTRAINT PK_BUY_GCARD PRIMARY KEY(GCARD_ID);
ALTER TABLE PURCHASE_GIFT_CARD ADD CONSTRAINT FK_PAY_GCARD FOREIGN KEY(TRANS_ID) REFERENCES TRANSACTIONS(TRANS_ID);
ALTER TABLE PURCHASE_GIFT_CARD ADD CONSTRAINT FK_GCARD_BUYED FOREIGN KEY(GCARD_ID) REFERENCES GIFT_CARD(GCARD_ID);
ALTER TABLE PURCHASE_GIFT_CARD ADD CONSTRAINT FK_CUST FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUST_ID);