DROP TABLE IF EXISTS TRANSACTIONS;
CREATE TABLE TRANSACTIONS
(
    TRANS_ID INT,
    PAY_METHOD VARCHAR(10),
    TOTAL_BALANCE DECIMAL(5,2)    
);
ALTER TABLE TRANS_ID ADD CONSTRAINT PK_PAY PRIMARY KEY(TRANS_ID);