DROP TABLE CERTIFICATION;
CREATE TABLE CERTIFICATION
(
    CERT_ID VARCHAR(4),
    CERT_NAME VARCHAR(20),
    DESCRIP VARCHAR(255)
);
ALTER TABLE CERTIFICATION ADD CONSTRAINT PK_CERT PRIMARY KEY(CERT_ID);
