DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER 
(
    CUST_ID INT,
    F_NAME VARCHAR(20),
    MI VARCHAR(1),
    L_NAME VARCHAR(20),
	GENDER VARCHAR(1)
);
ALTER TABLE CUSTOMER ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUST_ID);