DROP TABLE CUST_APPOINTMENT;
CREATE TABLE CUST_APPOINTMENT
(
    APPO_ID INT,
    CUST_ID INT,
    DATE_TIME_CREATED TIMESTAMP DEFAULT SYSDATE,
    DATE_TIME_APPOINT TIMESTAMP ,
    AREA_CODE VARCHAR(3),
    PHONE_NUM VARCHAR(8)
);
ALTER TABLE CUST_APPOINTMENT ADD CONSTRAINT PK_APPOINMENT PRIMARY KEY(APPO_ID);
ALTER TABLE CUST_APPOINTMENT ADD CONSTRAINT FK_CUSTOMER FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUST_ID);
