DROP TABLE ENTITLED;
CREATE TABLE ENTITLED
(
    CERT_ID VARCHAR(4),
    SERVICE_ID VARCHAR(4)
);
ALTER TABLE ENTITLED ADD CONSTRAINT PK_ENTITLE PRIMARY KEY(CERT_ID, SERVICE_ID);
ALTER TABLE ENTITLED ADD CONSTRAINT FK_CERTS FOREIGN KEY(CERT_ID) REFERENCES CERTIFICATION(CERT_ID);
ALTER TABLE ENTITLED ADD CONSTRAINT FK_SERVICES FOREIGN KEY(SERVICE_ID) REFERENCES "SERVICE"("ID");