DROP TABLE IF EXISTS GIFT_CARD;
CREATE TABLE GIFT_CARD 
(
GCARD_ID VARCHAR(4),
VALUE DECIMAL(5,2),
CUST_ID INT,
BUY_PRICE DECIMAL(5,2),
TRANS_ID INT
);
ALTER TABLE GIFT_CARD ADD CONSTRAINT PK_GCARD PRIMARY KEY (GCARD_ID);
ALTER TABLE GIFT_CARD ADD CONSTRAINT FK_CUST FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUST_ID);
ALTER TABLE GIFT_CARD ADD CONSTRAINT FK_TRANS FOREIGN KEY(TRANS_ID) REFERENCES TRANSACTIONS(TRANS_ID);
