DROP TABLE IF EXISTS NAIL_POLISH;
CREATE TABLE NAIL_POLISH
(
    POLISH_ID VARCHAR(5),
    TYPE VARCHAR(10),
    NAME VARCHAR(50),
    QTY INT,
    PRICE DECIMAL(5,2)
);
ALTER TABLE NAIL_POLISH ADD CONSTRAINT PK_NAIL_POLISH PRIMARY KEY(POLISH_ID);