DROP TABLE "ORDER";
CREATE TABLE "ORDER"
(
ORDER_ID INT,
SERVICE_ID VARCHAR(4),
CUST_ID INT,
EMP_ID VARCHAR(4),
APPO_ID INT,
TRANS_ID INT,
PRICE DECIMAL(5,2)
);
ALTER TABLE "ORDER" ADD CONSTRAINT PK_ORDER PRIMARY KEY(ORDER_ID);
ALTER TABLE "ORDER" ADD CONSTRAINT FK_CONSUMER FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUST_ID);
ALTER TABLE "ORDER" ADD CONSTRAINT FK_SERVICE FOREIGN KEY(SERVICE_ID) REFERENCES "SERVICE"("ID");
ALTER TABLE "ORDER" ADD CONSTRAINT FK_EMP_WORK FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(EMP_ID);
ALTER TABLE "ORDER" ADD CONSTRAINT FK_APPO FOREIGN KEY(APPO_ID) REFERENCES CUST_APPOINTMENT(APPO_ID);
ALTER TABLE "ORDER" ADD CONSTRAINT FK_TRANS FOREIGN KEY(TRANS_ID) REFERENCES TRANSACTIONS(TRANS_ID);

