DROP TABLE IF EXISTS ORDER_POLISH_USE;
CREATE TABLE ORDER_POLISH_USE
(
    ORDER_ID INT,
    POLISH_ID VARCHAR(5)
);
ALTER TABLE ORDER_POLISH_USE ADD CONSTRAINT PK_ORD_POL_USE PRIMARY KEY(ORDER_ID, POLISH_ID);
ALTER TABLE ORDER_POLISH_USE ADD CONSTRAINT FK_ORD FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID);
ALTER TABLE ORDER_POLISH_USE ADD CONSTRAINT FK_POLISH_USE FOREIGN KEY(POLISH_ID) REFERENCES NAIL_POLISH(POLISH_ID);