DROP TABLE PURCHASE_POLISH;
CREATE TABLE PURCHASE_POLISH
(
    POLISH_ID VARCHAR(5),
    CUST_ID INT,
    QTY INT,
    BALANCE DECIMAL(5,2),
    TRANS_ID INT
);
ALTER TABLE PURCHASE_POLISH ADD CONSTRAINT PK_PURCHASE PRIMARY KEY(POLISH_ID, CUST_ID);
ALTER TABLE PURCHASE_POLISH ADD CONSTRAINT FK_CUSTOMER_BUY_POLISH FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUST_ID);
ALTER TABLE PURCHASE_POLISH ADD CONSTRAINT FK_POLISH FOREIGN KEY(POLISH_ID) REFERENCES NAIL_POLISH(POLISH_ID);
ALTER TABLE PURCHASE_POLISH ADD CONSTRAINT FK_PAY_POLISH FOREIGN KEY(TRANS_ID) REFERENCES TRANSACTIONS(TRANS_ID);