DROP TABLE IF EXISTS SERVICE;
CREATE TABLE SERVICE
(
    ID VARCHAR(3),
    NAME VARCHAR(40),
    TYPE VARCHAR(15),
    PRICE DECIMAL(5,2)
);
ALTER TABLE SERVICE ADD CONSTRAINT PK_SERVICE PRIMARY KEY(ID);